package spotify

import (
	"context"
	"fmt"
	"log/slog"
)

// Service handles Spotify playlist creation.
type Service struct {
	client     *Client
	tokenStore *TokenStore
}

// NewService creates a new Spotify service.
func NewService(client *Client, tokenStore *TokenStore) *Service {
	return &Service{client: client, tokenStore: tokenStore}
}

// CreatePlaylist searches for songs and creates a Spotify playlist.
func (s *Service) CreatePlaylist(ctx context.Context, sessionID string, input PlaylistInput) (*PlaylistResult, error) {
	token, err := s.tokenStore.Get(sessionID)
	if err != nil {
		return nil, ErrNotAuthenticated
	}

	if token.IsExpired() {
		// In v1, no refresh — just require re-auth
		s.tokenStore.Delete(sessionID)
		return nil, ErrTokenExpired
	}

	// Get current user
	user, err := s.client.GetCurrentUser(ctx, token.AccessToken)
	if err != nil {
		return nil, err
	}

	// Search for songs
	var tracks []Track
	var notFound []string

	for _, songName := range input.Songs {
		track := s.searchSong(ctx, token.AccessToken, songName, input.ArtistName)
		if track != nil {
			tracks = append(tracks, *track)
		} else {
			notFound = append(notFound, songName)
		}
	}

	if len(tracks) == 0 {
		return nil, ErrNoSongsMatched
	}

	// Build playlist name
	name := playlistName(input.ArtistName, input.TourName)

	// Create playlist
	playlistID, playlistURL, err := s.client.CreatePlaylist(ctx, token.AccessToken, user.ID, name, "Predicted setlist generated by setlist-spotify")
	if err != nil {
		return nil, err
	}

	// Add tracks
	uris := make([]string, len(tracks))
	for i, t := range tracks {
		uris[i] = t.URI
	}
	if err := s.client.AddTracks(ctx, token.AccessToken, playlistID, uris); err != nil {
		return nil, err
	}

	return &PlaylistResult{
		PlaylistID:  playlistID,
		PlaylistURL: playlistURL,
		Name:        name,
		TracksAdded: len(tracks),
		TracksTotal: len(input.Songs),
		NotFound:    notFound,
	}, nil
}

func (s *Service) searchSong(ctx context.Context, accessToken, songName, artistName string) *Track {
	// Step 1: strict search
	query := fmt.Sprintf("track:%s artist:%s", songName, artistName)
	track, err := s.client.SearchTrack(ctx, accessToken, query)
	if err != nil {
		slog.Debug("strict search failed", "song", songName, "error", err)
	}
	if track != nil {
		return track
	}

	// Step 2: relaxed search
	query = fmt.Sprintf("%s %s", songName, artistName)
	track, err = s.client.SearchTrack(ctx, accessToken, query)
	if err != nil {
		slog.Debug("relaxed search failed", "song", songName, "error", err)
	}
	return track
}

func playlistName(artist, tour string) string {
	if tour != "" {
		return fmt.Sprintf("%s - %s (Predicted Setlist)", artist, tour)
	}
	return fmt.Sprintf("%s - Predicted Setlist", artist)
}
